-- MusicOn — seed de artistas de demo (sin owner_id: son de catálogo, no de un usuario real todavía)
-- Correr en Supabase Dashboard → SQL Editor → Run

insert into artists (name, genre, city, bio, photo_url, price_from, price_per, verified, pro_tier, members, travel_radius_km, tags) values
('The Midnight Set', 'Rock', 'Austin, TX', 'Four-piece indie rock band blending garage energy with melodic hooks. We have played 200+ weddings, corporate events, and festival slots across Texas.', 'https://images.pexels.com/photos/27773472/pexels-photo-27773472.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 1200, 'event', true, true, 4, 150, array['Weddings','Festivals','Corporate']),
('Lila Vance', 'Jazz', 'New Orleans, LA', 'Jazz vocalist with a velvet tone and a 300-song repertoire. Solo, duo, or trio setups available. Specialize in cocktail hours and intimate venues.', 'https://images.pexels.com/photos/9002796/pexels-photo-9002796.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 350, 'hour', true, true, 1, 80, array['Cocktail Hour','Private Events','Restaurants']),
('PULSE', 'Electronic', 'Los Angeles, CA', 'DJ and producer spinning house, tech, and disco edits. Full sound and lighting rig included. Resident at three LA clubs and available for private parties.', 'https://images.pexels.com/photos/3903095/pexels-photo-3903095.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 800, 'event', true, false, 1, 200, array['Clubs','Private Parties','Festivals']),
('Elena Costa', 'Classical', 'San Francisco, CA', 'Conservatory-trained violinist performing classical, baroque, and contemporary film scores. Available for weddings, galleries, and formal dinners.', 'https://images.pexels.com/photos/7097470/pexels-photo-7097470.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 400, 'hour', true, true, 1, 60, array['Weddings','Ceremonies','Galleries']),
('Marcus Reed', 'Jazz', 'Chicago, IL', 'Saxophonist fluent in jazz, funk, and R&B. Solo or with a trio. 15 years of gigging experience at clubs, weddings, and corporate galas.', 'https://images.pexels.com/photos/3984790/pexels-photo-3984790.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 450, 'hour', true, false, 1, 100, array['Cocktail Hour','Galas','Clubs']),
('Salt & Cedar', 'Folk', 'Portland, OR', 'Americana duo with harmonies and acoustic warmth. Perfect for barn weddings, breweries, and listening rooms. We bring our own PA.', 'https://images.pexels.com/photos/26986907/pexels-photo-26986907.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 600, 'event', false, false, 2, 120, array['Weddings','Breweries','Listening Rooms']),
('KOBE', 'Hip-Hop', 'Atlanta, GA', 'MC and producer bringing high-energy sets and freestyle skills. Opened for national tours. Available for parties, brand events, and showcases.', 'https://images.pexels.com/photos/27290241/pexels-photo-27290241.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 700, 'event', true, true, 1, 250, array['Parties','Brand Events','Showcases']),
('Sofia Reyes', 'Acoustic', 'Nashville, TN', 'Singer-songwriter with a warm, soulful voice. Covers and originals for coffee shops, private dinners, and intimate ceremonies.', 'https://images.pexels.com/photos/28278006/pexels-photo-28278006.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 250, 'hour', true, false, 1, 70, array['Coffee Shops','Private Dinners','Ceremonies']),
('The Vinyl Hours', 'Pop', 'Denver, CO', 'Five-piece cover band playing hits from every decade. We read the room and keep the dance floor full. Full lighting and PA included.', 'https://images.pexels.com/photos/19262062/pexels-photo-19262062.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 1800, 'event', true, true, 5, 180, array['Weddings','Corporate','Festivals']),
('Mateo Silva', 'Latin', 'Miami, FL', 'Guitarist and vocalist specializing in bossa nova, boleros, and Latin jazz. Perfect for rooftop cocktail hours, wineries, and private dining.', 'https://images.pexels.com/photos/27638361/pexels-photo-27638361.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 300, 'hour', true, false, 1, 90, array['Cocktail Hour','Wineries','Private Dining']),
('Clara Bishop', 'Blues', 'Memphis, TN', 'Blues guitarist and vocalist with a raw, soulful sound. Solo, duo, or full band. We have held residencies at three Beale Street venues.', 'https://images.pexels.com/photos/8043896/pexels-photo-8043896.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 500, 'event', false, false, 1, 110, array['Clubs','Festivals','Private Events']),
('Echo Park', 'Electronic', 'Brooklyn, NY', 'Live electronic duo blending synth textures with live percussion. We bring a full visual rig and tailor every set to the room.', 'https://images.pexels.com/photos/5203816/pexels-photo-5203816.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 950, 'event', true, true, 2, 160, array['Clubs','Galleries','Private Parties']);
